### ISSUE TITLE
Can sbt-resolver be used with Intellij?

### ISSUE THREAD

**Issue by aliakhtar** [spray/sbt-revolver#88]
Sorry if this is the wrong place to ask, I saw some answers but all were from a few years ago.

Can sbt-resolver be used with IntelliJ? If there's a way to recompile the files which change, that could speed up dev times a lot.

**Comment by aliakhtar** [comment]
Could I just run it in a forked jvm and it will auto compile files that change?

**Comment by jrudolph** [comment]
Yes, the plugin works since a few years unchanged, so the old answers should mostly still be valid. You usually use the plugin from inside sbt whether you run it in IntelliJ or from the command line shouldn't make a difference.

See https://github.com/spray/sbt-revolver#triggered-restart for more info.

**Comment by aliakhtar** [comment]
I can't figure out the difference between triggered and normal `reStart`, is the difference only that `~reStart` shows the output in the terminal while `reStart` creates a forked process which runs in background, but they both basically do the same thing (recompiling whenever source files change)?
